environment:
  name: local
server:
  port: 9000
  allowed_origins: http://localhost:4200,http://localhost:9000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3309/rideshare
    username: root
    password: t00R
    driver-class-name: com.mysql.cj.jdbc.Driver